### ISSUE TITLE
Looking for Non-Code Contribution: Write a README.md File

### ISSUE THREAD

**Issue by DejavuByte** [DejavuByte/Movie-Search-App#2]
We’re looking to add a README.md file to our project! This file will serve as a guide for anyone who visits our repository, helping them understand what the project is about, how to set it up, and how they can get involved.

What We Need:
If you’re good at writing or enjoy organizing information, this is a great way to contribute! We need someone to:

Explain what the app does (it's a movie search app using the OMDb API).
List the key features (e.g., search by movie title, display results).
Provide instructions on how to install and run the project.
Include details on where to get an API key and how to add it.
Suggest ways people can contribute and link to any relevant guidelines.
Who Can Help:
This is perfect if you’re not into coding but want to help out! It’s also a great opportunity for first-time open source contributors. If you’re unsure about anything, feel free to ask questions—everyone is welcome to jump in.

We’d love your input!

**Comment by avbhutani** [comment]
Can you please assign it to me?

**Comment by DejavuByte** [comment]
Hey, @avbhutani, Please give me update on this.

**Comment by devjainofficial** [comment]
@DejavuByte 
Assign it to me
