### ISSUE TITLE
Create a SearchBar Component for Movie Search

### ISSUE THREAD

**Issue by DejavuByte** [DejavuByte/Movie-Search-App#4]
We need a SearchBar component where users can input the movie title they want to search for. This component should have:

An input field for entering the movie title.
A search button to trigger the API request based on the entered query.

Requirements:
Use React's useState to manage the input value.
When the user presses the search button, the input value should be passed to the parent component, triggering a movie search.
Add basic styling to ensure the SearchBar is user-friendly.

Who Can Help:
If you enjoy working with React components and handling user input, this is a great task to contribute to! Feel free to ask any questions if something isn’t clear.

**Comment by devjainofficial** [comment]
Please Assign me.
