### ISSUE TITLE
Create a MovieCard Component to Display Movie Details

### ISSUE THREAD

**Issue by DejavuByte** [DejavuByte/Movie-Search-App#6]
We need a MovieCard component to display individual movie details like the title, year, poster, and type (movie, series, etc.).

Requirements:
The component should receive a single movie's data as a prop and display:
Movie poster.
Movie title.
Release year.
Type (movie, series, etc.).
Add basic styling to make the card visually appealing (e.g., using borders, margins, and padding).
Make sure the movie poster is properly sized and the layout is responsive.

Who Can Help:
If you like building reusable components in React and enjoy working on visual UI elements, this task is for you! We welcome any questions or feedback.

**Comment by Zish303** [comment]
@DejavuByte I want to work on this feature.
